.Dd June 26, 2026
.Dt VSBSDLINFO 1
.Os
.Sh NAME
.Nm vsbsdlinfo
.Nd determines information about a BSD disklabel volume system
.Sh SYNOPSIS
.Nm vsbsdlinfo
.Op Fl o Ar offset
.Op Fl hvV
.Ar source
.Sh DESCRIPTION
.Nm vsbsdlinfo
is a utility to determine information about a BSD disklabel volume system
.Pp
.Nm vsbsdlinfo
is part of the
.Nm libvsbsdl
package.
.Nm libvsbsdl
is a library to access the BSD disklabel volume system format
.Pp
.Ar source
is the source image.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
shows this help
.It Fl o Ar offset
specify the volume offset in bytes
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# vsbsdlinfo /dev/sda
vsbsdlinfo 20260626
.sp
BSD disklabel information:
	Bytes per sector	: 512
	Number of partitions	: 2
.sp
Partition: 1
	Name			: a
	Offset			: 8192 (0x00002000)
	Size			: 4186112
.sp
Partition: 3
	Name			: c
	Offset			: 0 (0x00000000)
	Size			: 4194304
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \
\-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libvsbsdl/issues
.Sh COPYRIGHT
Copyright (C) 2023-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
